version: '3'

services:
  trot_node:
    image: node:14-alpine
    restart: unless-stopped
    working_dir: /home/node
    env_file: .env
    ports:
      - "80:8080"
    volumes:
      - .:/home/node
    networks:
      - app-network
    command: "npm start"

  trot_db:
    image: mongo:4.0.25-xenial
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: